# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StepWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(224, 199)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(224, 199))
        MainWindow.setMaximumSize(QtCore.QSize(224, 199))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 191, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.x_step_value = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.x_step_value.setObjectName("x_step_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.x_step_value)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.y_step_value = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.y_step_value.setObjectName("y_step_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.y_step_value)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.send_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.send_button.setObjectName("send_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.send_button)
        self.y_step_value_2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.y_step_value_2.setObjectName("y_step_value_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.y_step_value_2)
        self.y_step_value_3 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.y_step_value_3.setDecimals(0)
        self.y_step_value_3.setObjectName("y_step_value_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.y_step_value_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Step Setter"))
        self.label.setText(_translate("MainWindow", "X step"))
        self.label_2.setText(_translate("MainWindow", "Y step"))
        self.label_3.setText(_translate("MainWindow", "Threshold"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.label_4.setText(_translate("MainWindow", "Time"))
